<a href="https://colab.research.google.com/github/MariaMoraru/Dissertation/blob/main/Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Airlines.csv to Airlines.csv


In [ ]:
!python --version

Python 3.7.13


In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes

In [ ]:
!cat /proc/meminfo

MemTotal:       13297228 kB
MemFree:        10644952 kB
MemAvailable:   12324920 kB
Buffers:           59884 kB
Cached:          1747976 kB
SwapCached:            0 kB
Active:           435212 kB
Inactive:        2052476 kB
Active(anon):        960 kB
Inactive(anon):   600936 kB
Active(file):     434252 kB
Inactive(file):  1451540 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               324 kB
Writeback:             0 kB
AnonPages:        679900 kB
Mapped:           229744 kB
Shmem:              1256 kB
KReclaimable:      71252 kB
Slab:              99456 kB
SReclaimable:      71252 kB
SUnreclaim:        28204 kB
KernelStack:        4432 kB
PageTables:        13888 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6648612 kB
Committed_AS:    2972676 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        9268 kB
VmallocChunk:          0 kB
Percpu:          

In [ ]:
!df -h

Filesystem      Size  Used Avail Use% Mounted on
overlay         108G   37G   71G  35% /
tmpfs            64M     0   64M   0% /dev
shm             5.8G     0  5.8G   0% /dev/shm
/dev/root       2.0G  1.1G  910M  54% /sbin/docker-init
tmpfs           6.4G   28K  6.4G   1% /var/colab
/dev/sda1        80G   38G   42G  48% /etc/hosts
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware


In [ ]:
import pandas as pd
mydata = pd.read_csv('Airlines.csv')
#mydata = mydata[:20]
mydata.shape

(539383, 9)

In [ ]:
# first neural network with keras tutorial
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# split data into X and y
#create a dataframe with all training data except the target column
X = mydata.drop(columns=['id', 'Airline','AirportFrom','AirportTo','Delay'])

#check that the target variable has been removed
X.head()

Flight  DayOfWeek  Time  Length
0     269          3    15     205
1    1558          3    15     222
2    2400          3    20     165
3    2466          3    20     195
4     108          3    30     202

In [ ]:
#separate target values
y = mydata['Delay'].values

#view target values
y[0:5]

array([1, 1, 1, 1, 0])

In [ ]:
from sklearn.model_selection import train_test_split

#split dataset into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)

In [ ]:
# define the keras model
model = Sequential()
model.add(Dense(12, input_shape=(4,), activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 12)                60        
                                                                 
 dense_4 (Dense)             (None, 4)                 52        
                                                                 
 dense_5 (Dense)             (None, 4)                 20        
                                                                 
 dense_6 (Dense)             (None, 1)                 5         
                                                                 
Total params: 137
Trainable params: 137
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# fit the keras model on the dataset
model.fit(X_train, y_train, epochs=15, batch_size=10)

Epoch 1/15
43151/43151 [==============================] - 82s 2ms/step - loss: 0.7895 - accuracy: 0.5532
Epoch 2/15
43151/43151 [==============================] - 82s 2ms/step - loss: 0.6872 - accuracy: 0.5546
Epoch 3/15
43151/43151 [==============================] - 83s 2ms/step - loss: 0.6872 - accuracy: 0.5546
Epoch 4/15
43151/43151 [==============================] - 82s 2ms/step - loss: 0.6872 - accuracy: 0.5546
Epoch 5/15
43151/43151 [==============================] - 81s 2ms/step - loss: 0.6873 - accuracy: 0.5546
Epoch 6/15
43151/43151 [==============================] - 81s 2ms/step - loss: 0.6872 - accuracy: 0.5546
Epoch 7/15
43151/43151 [==============================] - 81s 2ms/step - loss: 0.6872 - accuracy: 0.5546
Epoch 8/15
43151/43151 [==============================] - 81s 2ms/step - loss: 0.6872 - accuracy: 0.5546
Epoch 9/15
43151/43151 [==============================] - 81s 2ms/step - loss: 0.6872 - accuracy: 0.5546
Epoch 10/15
43151/43151 [==============================

In [ ]:
y_pred_test = model.predict(X_test)

In [ ]:
# evaluate the keras model
accuracy = model.evaluate(y_test, y_pred_test)
print('Accuracy: %.2f' % (accuracy*100))

ValueError: ignored

In [ ]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X_train, y_train)

# Make predictions for the test set
y_pred_test = clf.predict(X_test)
y_pred_test

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
#clf.predict_proba(y_test, y_pred_test)
pd.DataFrame(clf.predict_proba(y_test), columns=clf.classes_)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"


ValueError: ignored

In [ ]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
y_pred_test

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# View accuracy score
accuracy_score(y_test, y_pred_test)

0.55455750530697

In [ ]:
confusion_matrix(y_test, y_pred_test)

array([[59824,     0],
       [48053,     0]])

In [ ]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.55      1.00      0.71     59824
           1       0.00      0.00      0.00     48053

    accuracy                           0.55    107877
   macro avg       0.28      0.50      0.36    107877
weighted avg       0.31      0.55      0.40    107877



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
